- hosts: all
  remote_user: root
  become: true

  vars:
    USERS:
      - username: admin
      - username: john
    SWAP_LOCATION: /.SWAP
    SWAP_SIZE: 50

  roles:
    - nginx_app
    - create_user
    - create_swap
