---
# tasks file for nginx_app
- name: Installs Nginx
  apt: 
    pkg: nginx 
    state: installed
    update_cache: true
  notify:
    - Start Nginx

- name: copy index file
  template: 
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0777
