---
# tasks file for nginx_app
- name: Installs Nginx
  apt: 
    pkg: nginx 
    state: installed
    update_cache: true
  notify:
    - Start Nginx
# name: install epel-release
# yum: 
#   name: epel-release
#   state: latest

- name: copy index file
  template: 
    src: index.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0777
#  - name: Install dumb init
#      get_url:
#        dest: /usr/bin/dumb-init
#        url: https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
#        mode: 0775
#        validate_certs: no    
