---
# tasks file for create_user
- name: create users    
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    state: present
  with_items: "{{USERS}}"
    
- name: upload ssh key                
  authorized_key:
    user: "{{ item.username }}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file', 'files/{{ item.username }}.pub') }}"
  with_items:
    - "{{ USERS }}"
 
